In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

## Задание 11.1 — Series

In [3]:
# 1
missions = ['Apollo 11', 'Voyager 1', 'Mars Pathfinder', 'Cassini-Huygens', 'Kepler']
mission_ids = ['M01', 'M02', 'M03', 'M04', 'M05']

series1 = pd.Series(missions, index=mission_ids, dtype='string', name='Название миссии')
print('Series №1:')
print(series1)

Series №1:
M01          Apollo 11
M02          Voyager 1
M03    Mars Pathfinder
M04    Cassini-Huygens
M05             Kepler
Name: Название миссии, dtype: string

In [4]:
# 2
agencies = ['NASA', 'NASA', 'NASA', 'NASA/ESA/ASI', 'NASA']
series2 = pd.Series(agencies, index=mission_ids, dtype='string', name='Агентство')
print('Series №2:')
print(series2)

Series №2:
M01            NASA
M02            NASA
M03            NASA
M04    NASA/ESA/ASI
M05            NASA
Name: Агентство, dtype: string

In [5]:
# 3
costs = [25.4, 0.865, 0.265, 3.26, 0.600]
series3 = pd.Series(costs, index=mission_ids, dtype='float64', name='Стоимость, млрд $')
print('Series №3:')
print(series3)

Series №3:
M01    25.400
M02     0.865
M03     0.265
M04     3.260
M05     0.600
Name: Стоимость, млрд $, dtype: float64

In [6]:
# 4
series4 = pd.Series(
    [f'{series1.loc[i]} — {series2.loc[i]}' for i in mission_ids],
    index=mission_ids,
    dtype='string',
    name='Миссия и агентство'
)
print('Series №4:')
print(series4)

Series №4:
M01                  Apollo 11 — NASA
M02                  Voyager 1 — NASA
M03            Mars Pathfinder — NASA
M04    Cassini-Huygens — NASA/ESA/ASI
M05                     Kepler — NASA
Name: Миссия и агентство, dtype: string

In [7]:
# 5
print('Максимальная стоимость:', series3.max())
print('Минимальная стоимость:', series3.min())
print('Средняя стоимость:', series3.mean())

Максимальная стоимость: 25.4
Минимальная стоимость: 0.265
Средняя стоимость: 6.078

## Задание 11.2 — DataFrame

In [8]:
# 1
launch_dates = pd.to_datetime([
    '1969-07-16', '1977-09-05', '1996-12-04', '1997-10-15', '2009-03-07'
])

targets = ['Луна', 'Межзвёздное пространство', 'Марс', 'Сатурн', 'Экзопланеты']
durations = ['8 дней', '49+ лет', '7 месяцев', '19 лет 11 месяцев', '9 лет 7 месяцев']

df1 = pd.DataFrame({
    'Дата запуска': launch_dates,
    'Цель': targets,
    'Продолжительность': durations
}, index=mission_ids)

print('DataFrame №1:')
display(df1)

DataFrame №1:

    Дата запуска                      Цель  Продолжительность
M01   1969-07-16                      Луна             8 дней
M02   1977-09-05  Межзвёздное пространство            49+ лет
M03   1996-12-04                      Марс          7 месяцев
M04   1997-10-15                    Сатурн  19 лет 11 месяцев
M05   2009-03-07               Экзопланеты    9 лет 7 месяцев

In [9]:
# 2
df2 = pd.concat([series1, series2, series3], axis=1)
print('DataFrame №2:')
display(df2)

DataFrame №2:

     Название миссии     Агентство  Стоимость, млрд $
M01        Apollo 11          NASA             25.400
M02        Voyager 1          NASA              0.865
M03  Mars Pathfinder          NASA              0.265
M04  Cassini-Huygens  NASA/ESA/ASI              3.260
M05           Kepler          NASA              0.600

In [10]:
# 3
df3 = pd.concat([df1, df2], axis=1)
print('DataFrame №3:')
display(df3)

DataFrame №3:

    Дата запуска                      Цель  Продолжительность  Название миссии     Агентство  Стоимость, млрд $
M01   1969-07-16                      Луна             8 дней        Apollo 11          NASA             25.400
M02   1977-09-05  Межзвёздное пространство            49+ лет        Voyager 1          NASA              0.865
M03   1996-12-04                      Марс          7 месяцев  Mars Pathfinder          NASA              0.265
M04   1997-10-15                    Сатурн  19 лет 11 месяцев  Cassini-Huygens  NASA/ESA/ASI              3.260
M05   2009-03-07               Экзопланеты    9 лет 7 месяцев           Kepler          NASA              0.600

In [11]:
# 4
print('Метки строк:')
print(df3.index.tolist())

print('\nМетки столбцов:')
print(df3.columns.tolist())

print('\nМассив данных:')
print(df3.to_numpy())

Метки строк:
['M01', 'M02', 'M03', 'M04', 'M05']

Метки столбцов:
['Дата запуска', 'Цель', 'Продолжительность', 'Название миссии', 'Агентство', 'Стоимость, млрд $']

Массив данных:
[[Timestamp('1969-07-16 00:00:00') 'Луна' '8 дней' 'Apollo 11' 'NASA'
  25.4]
 [Timestamp('1977-09-05 00:00:00') 'Межзвёздное пространство' '49+ лет'
  'Voyager 1' 'NASA' 0.865]
 [Timestamp('1996-12-04 00:00:00') 'Марс' '7 месяцев' 'Mars Pathfinder'
  'NASA' 0.265]
 [Timestamp('1997-10-15 00:00:00') 'Сатурн' '19 лет 11 месяцев'
  'Cassini-Huygens' 'NASA/ESA/ASI' 3.26]
 [Timestamp('2009-03-07 00:00:00') 'Экзопланеты' '9 лет 7 месяцев'
  'Kepler' 'NASA' 0.6]]

In [12]:
# 5а
print('Первые две строки:')
display(df3.iloc[:2])

# 5б
print('Строки со второй по четвёртую:')
display(df3.iloc[1:4])

# 5в
print('Названия миссий:')
display(df3['Название миссии'])

# 5г
print('Стоимость миссий:')
display(df3['Стоимость, млрд $'])

# 5д
selected_id = 'M03'
print(f'Название миссии {selected_id}:', df3.loc[selected_id, 'Название миссии'])

# 5е
number = 4
print(f'Агентство миссии №{number}:', df3.iloc[number - 1]['Агентство'])

Первые две строки:

    Дата запуска                      Цель Продолжительность Название миссии Агентство  Стоимость, млрд $
M01   1969-07-16                      Луна            8 дней       Apollo 11      NASA             25.400
M02   1977-09-05  Межзвёздное пространство           49+ лет       Voyager 1      NASA              0.865

Строки со второй по четвёртую:

    Дата запуска                      Цель  Продолжительность  Название миссии     Агентство  Стоимость, млрд $
M02   1977-09-05  Межзвёздное пространство            49+ лет        Voyager 1          NASA              0.865
M03   1996-12-04                      Марс          7 месяцев  Mars Pathfinder          NASA              0.265
M04   1997-10-15                    Сатурн  19 лет 11 месяцев  Cassini-Huygens  NASA/ESA/ASI              3.260

Названия миссий:

M01          Apollo 11
M02          Voyager 1
M03    Mars Pathfinder
M04    Cassini-Huygens
M05             Kepler
Name: Название миссии, dtype: string

Стоимость миссий:

M01    25.400
M02     0.865
M03     0.265
M04     3.260
M05     0.600
Name: Стоимость, млрд $, dtype: float64

Название миссии M03: Mars Pathfinder
Агентство миссии №4: NASA/ESA/ASI

## Задание 11.3 — обработка данных о курсе акций

In [13]:
stock_raw = pd.DataFrame({
    'Date': ['2026-09-21','2026-09-22','2026-09-23','2026-09-24','2026-09-25',
             '2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02'],
    'Open':  ['$101.50', '$103.20', None, '$102.10', '$105.30', '$106.20', '$107.10', None, '$109.00', '$110.40'],
    'High':  ['$104.20', '$105.00', '$104.80', '$106.30', '$108.00', '$108.40', '$110.20', '$111.00', '$112.50', '$113.00'],
    'Low':   ['$100.80', '$101.70', '$100.50', '$101.20', None, '$104.80', '$105.90', '$107.00', '$108.20', '$109.50'],
    'Close': ['$103.80', '$102.40', '$103.10', '$105.90', '$107.20', None, '$109.40', '$110.10', '$111.70', '$112.30'],
    'Volume':[1200000, 980000, 1150000, None, 1300000, 1280000, 1400000, 1380000, None, 1500000]
})
stock_raw.to_csv('stocks_2026.csv', index=False)
display(stock_raw)

         Date     Open     High      Low    Close     Volume
0  2026-09-21  $101.50  $104.20  $100.80  $103.80  1200000.0
1  2026-09-22  $103.20  $105.00  $101.70  $102.40   980000.0
2  2026-09-23      NaN  $104.80  $100.50  $103.10  1150000.0
3  2026-09-24  $102.10  $106.30  $101.20  $105.90        NaN
4  2026-09-25  $105.30  $108.00      NaN  $107.20  1300000.0
5  2026-09-28  $106.20  $108.40  $104.80      NaN  1280000.0
6  2026-09-29  $107.10  $110.20  $105.90  $109.40  1400000.0
7  2026-09-30      NaN  $111.00  $107.00  $110.10  1380000.0
8  2026-10-01  $109.00  $112.50  $108.20  $111.70        NaN
9  2026-10-02  $110.40  $113.00  $109.50  $112.30  1500000.0

In [14]:
# 1. Чтение CSV

def money_to_float(value):
    if pd.isna(value) or str(value).strip() == '':
        return np.nan
    text = str(value).replace('$', '').replace('€', '').replace('£', '').strip()
    return float(text)

stock = pd.read_csv(
    'stocks_2026.csv',
    header=0,
    usecols=['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
    parse_dates=['Date'],
    converters={
        'Open': money_to_float,
        'High': money_to_float,
        'Low': money_to_float,
        'Close': money_to_float
    },
    decimal='.'
)

stock['Volume'] = pd.to_numeric(stock['Volume'], errors='coerce').astype('Float64')

print(stock.dtypes)
display(stock)

Date      datetime64[us]
Open             float64
High             float64
Low              float64
Close            float64
Volume           Float64
dtype: object

        Date   Open   High    Low  Close     Volume
0 2026-09-21  101.5  104.2  100.8  103.8  1200000.0
1 2026-09-22  103.2  105.0  101.7  102.4   980000.0
2 2026-09-23    NaN  104.8  100.5  103.1  1150000.0
3 2026-09-24  102.1  106.3  101.2  105.9       <NA>
4 2026-09-25  105.3  108.0    NaN  107.2  1300000.0
5 2026-09-28  106.2  108.4  104.8    NaN  1280000.0
6 2026-09-29  107.1  110.2  105.9  109.4  1400000.0
7 2026-09-30    NaN  111.0  107.0  110.1  1380000.0
8 2026-10-01  109.0  112.5  108.2  111.7       <NA>
9 2026-10-02  110.4  113.0  109.5  112.3  1500000.0

In [15]:
# 2а
sorted_stock = stock.sort_values('Volume', ascending=False)
display(sorted_stock)

        Date   Open   High    Low  Close     Volume
9 2026-10-02  110.4  113.0  109.5  112.3  1500000.0
6 2026-09-29  107.1  110.2  105.9  109.4  1400000.0
7 2026-09-30    NaN  111.0  107.0  110.1  1380000.0
4 2026-09-25  105.3  108.0    NaN  107.2  1300000.0
5 2026-09-28  106.2  108.4  104.8    NaN  1280000.0
0 2026-09-21  101.5  104.2  100.8  103.8  1200000.0
2 2026-09-23    NaN  104.8  100.5  103.1  1150000.0
1 2026-09-22  103.2  105.0  101.7  102.4   980000.0
3 2026-09-24  102.1  106.3  101.2  105.9       <NA>
8 2026-10-01  109.0  112.5  108.2  111.7       <NA>

In [16]:
# 2б
stock['Close_rank'] = stock['Close'].rank(ascending=False, method='min')
display(stock[['Date', 'Close', 'Close_rank']])

        Date  Close  Close_rank
0 2026-09-21  103.8         7.0
1 2026-09-22  102.4         9.0
2 2026-09-23  103.1         8.0
3 2026-09-24  105.9         6.0
4 2026-09-25  107.2         5.0
5 2026-09-28    NaN         NaN
6 2026-09-29  109.4         4.0
7 2026-09-30  110.1         3.0
8 2026-10-01  111.7         2.0
9 2026-10-02  112.3         1.0

In [17]:
# 2в
display(stock[['Open', 'High', 'Low', 'Close']].describe())

             Open        High         Low       Close
count    8.000000   10.000000    9.000000    9.000000
mean   105.600000  108.340000  104.400000  107.322222
std      3.209806    3.243181    3.451811    3.749593
min    101.500000  104.200000  100.500000  102.400000
25%    102.925000  105.325000  101.200000  103.800000
50%    105.750000  108.200000  104.800000  107.200000
75%    107.575000  110.800000  107.000000  110.100000
max    110.400000  113.000000  109.500000  112.300000

In [18]:
# 2г
pair = stock[['Close', 'Volume']].astype(float)

print('Корреляция:')
display(pair.corr())

print('Ковариация:')
display(pair.cov())

Корреляция:

           Close    Volume
Close   1.000000  0.954094
Volume  0.954094  1.000000

Ковариация:

                Close        Volume
Close       14.059444  6.510000e+05
Volume  651000.000000  2.659821e+10

In [19]:
# 2д
rows_to_drop = stock[stock.isna().sum(axis=1) >= 2]
print('Строки с 2 и более пропусками:')
display(rows_to_drop)

cleaned = stock.dropna(thresh=stock.shape[1] - 1).copy()

numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']
for col in numeric_cols:
    cleaned[col] = cleaned[col].fillna(cleaned[col].mean())

print('После обработки пропусков:')
display(cleaned)

Строки с 2 и более пропусками:

        Date   Open   High    Low  Close     Volume  Close_rank
5 2026-09-28  106.2  108.4  104.8    NaN  1280000.0         NaN

После обработки пропусков:

        Date        Open   High     Low  Close          Volume  Close_rank
0 2026-09-21  101.500000  104.2  100.80  103.8       1200000.0         7.0
1 2026-09-22  103.200000  105.0  101.70  102.4        980000.0         9.0
2 2026-09-23  105.514286  104.8  100.50  103.1       1150000.0         8.0
3 2026-09-24  102.100000  106.3  101.20  105.9  1272857.142857         6.0
4 2026-09-25  105.300000  108.0  104.35  107.2       1300000.0         5.0
6 2026-09-29  107.100000  110.2  105.90  109.4       1400000.0         4.0
7 2026-09-30  105.514286  111.0  107.00  110.1       1380000.0         3.0
8 2026-10-01  109.000000  112.5  108.20  111.7  1272857.142857         2.0
9 2026-10-02  110.400000  113.0  109.50  112.3       1500000.0         1.0

## Задание 11.3, пункт 3 — объединение данных за другой неперекрывающийся период

In [20]:
stock_previous = pd.DataFrame({
    'Date': pd.to_datetime(['2026-09-16','2026-09-17','2026-09-18']),
    'Open': [98.0, 99.2, 100.1],
    'High': [100.0, 101.3, 102.2],
    'Low': [97.5, 98.7, 99.4],
    'Close': [99.4, 100.7, 101.8],
    'Volume': [900000, 950000, 1100000]
})

# 3а
concat_non_overlap = pd.concat(
    [stock_previous, stock.drop(columns=['Close_rank'])],
    ignore_index=True
)
print('concat() для неперекрывающихся периодов:')
display(concat_non_overlap)

# 3б
merge_non_overlap = pd.merge(
    stock_previous,
    stock.drop(columns=['Close_rank']),
    on=['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
    how='outer'
).sort_values('Date').reset_index(drop=True)

print('merge() для неперекрывающихся периодов:')
display(merge_non_overlap)

concat() для неперекрывающихся периодов:

         Date   Open   High    Low  Close     Volume
0  2026-09-16   98.0  100.0   97.5   99.4   900000.0
1  2026-09-17   99.2  101.3   98.7  100.7   950000.0
2  2026-09-18  100.1  102.2   99.4  101.8  1100000.0
3  2026-09-21  101.5  104.2  100.8  103.8  1200000.0
4  2026-09-22  103.2  105.0  101.7  102.4   980000.0
5  2026-09-23    NaN  104.8  100.5  103.1  1150000.0
6  2026-09-24  102.1  106.3  101.2  105.9       <NA>
7  2026-09-25  105.3  108.0    NaN  107.2  1300000.0
8  2026-09-28  106.2  108.4  104.8    NaN  1280000.0
9  2026-09-29  107.1  110.2  105.9  109.4  1400000.0
10 2026-09-30    NaN  111.0  107.0  110.1  1380000.0
11 2026-10-01  109.0  112.5  108.2  111.7       <NA>
12 2026-10-02  110.4  113.0  109.5  112.3  1500000.0

merge() для неперекрывающихся периодов:

         Date   Open   High    Low  Close     Volume
0  2026-09-16   98.0  100.0   97.5   99.4   900000.0
1  2026-09-17   99.2  101.3   98.7  100.7   950000.0
2  2026-09-18  100.1  102.2   99.4  101.8  1100000.0
3  2026-09-21  101.5  104.2  100.8  103.8  1200000.0
4  2026-09-22  103.2  105.0  101.7  102.4   980000.0
5  2026-09-23    NaN  104.8  100.5  103.1  1150000.0
6  2026-09-24  102.1  106.3  101.2  105.9       <NA>
7  2026-09-25  105.3  108.0    NaN  107.2  1300000.0
8  2026-09-28  106.2  108.4  104.8    NaN  1280000.0
9  2026-09-29  107.1  110.2  105.9  109.4  1400000.0
10 2026-09-30    NaN  111.0  107.0  110.1  1380000.0
11 2026-10-01  109.0  112.5  108.2  111.7       <NA>
12 2026-10-02  110.4  113.0  109.5  112.3  1500000.0

## Задание 11.3, пункт 4 — объединение данных за перекрывающийся период без дублирования

In [21]:
stock_overlap = pd.DataFrame({
    'Date': pd.to_datetime(['2026-09-29','2026-09-30','2026-10-01','2026-10-05']),
    'Open': [107.1, 108.2, 109.0, 113.0],
    'High': [110.2, 111.0, 112.5, 115.0],
    'Low': [105.9, 107.0, 108.2, 112.0],
    'Close': [109.4, 110.1, 111.7, 114.2],
    'Volume': [1400000, 1380000, 1450000, 1600000]
})

current = stock.drop(columns=['Close_rank']).copy()

# 4а
concat_overlap = (
    pd.concat([current, stock_overlap], ignore_index=True)
      .drop_duplicates(subset='Date', keep='last')
      .sort_values('Date')
      .reset_index(drop=True)
)
print('concat() без дублирования:')
display(concat_overlap)

# 4б
merge_overlap = (
    current.set_index('Date')
    .combine_first(stock_overlap.set_index('Date'))
    .sort_index()
    .reset_index()
)
print('Реляционное объединение без дублирования:')
display(merge_overlap)

concat() без дублирования:

         Date   Open   High    Low  Close     Volume
0  2026-09-21  101.5  104.2  100.8  103.8  1200000.0
1  2026-09-22  103.2  105.0  101.7  102.4   980000.0
2  2026-09-23    NaN  104.8  100.5  103.1  1150000.0
3  2026-09-24  102.1  106.3  101.2  105.9       <NA>
4  2026-09-25  105.3  108.0    NaN  107.2  1300000.0
5  2026-09-28  106.2  108.4  104.8    NaN  1280000.0
6  2026-09-29  107.1  110.2  105.9  109.4  1400000.0
7  2026-09-30  108.2  111.0  107.0  110.1  1380000.0
8  2026-10-01  109.0  112.5  108.2  111.7  1450000.0
9  2026-10-02  110.4  113.0  109.5  112.3  1500000.0
10 2026-10-05  113.0  115.0  112.0  114.2  1600000.0

Реляционное объединение без дублирования:

         Date   Open   High    Low  Close     Volume
0  2026-09-21  101.5  104.2  100.8  103.8  1200000.0
1  2026-09-22  103.2  105.0  101.7  102.4   980000.0
2  2026-09-23    NaN  104.8  100.5  103.1  1150000.0
3  2026-09-24  102.1  106.3  101.2  105.9       <NA>
4  2026-09-25  105.3  108.0    NaN  107.2  1300000.0
5  2026-09-28  106.2  108.4  104.8    NaN  1280000.0
6  2026-09-29  107.1  110.2  105.9  109.4  1400000.0
7  2026-09-30  108.2  111.0  107.0  110.1  1380000.0
8  2026-10-01  109.0  112.5  108.2  111.7  1450000.0
9  2026-10-02  110.4  113.0  109.5  112.3  1500000.0
10 2026-10-05  113.0  115.0  112.0  114.2  1600000.0

## Задание 11.3, пункт 5 — объединение с данными другой акции

In [22]:
other_stock = pd.DataFrame({
    'Date': pd.to_datetime(['2026-09-21','2026-09-22','2026-09-23','2026-09-24','2026-09-25']),
    'Open': [55.0, 55.8, 56.1, 55.6, 57.0],
    'High': [56.2, 56.5, 57.0, 57.2, 58.1],
    'Low': [54.5, 55.1, 55.4, 55.0, 56.3],
    'Close': [55.9, 56.0, 56.7, 56.8, 57.6],
    'Volume': [700000, 720000, 690000, 750000, 810000]
})

stock_a = current.copy()
stock_a['Ticker'] = 'PETR'
stock_b = other_stock.copy()
stock_b['Ticker'] = 'OTHER'

# 5а.
two_stocks_concat = pd.concat([stock_a, stock_b], ignore_index=True)
print('Две акции через concat():')
display(two_stocks_concat)

# 5б.
two_stocks_merge = pd.merge(
    stock_a,
    stock_b,
    on='Date',
    how='outer',
    suffixes=('_PETR', '_OTHER')
).sort_values('Date').reset_index(drop=True)

print('Две акции через merge():')
display(two_stocks_merge)

Две акции через concat():

         Date   Open   High    Low  Close     Volume Ticker
0  2026-09-21  101.5  104.2  100.8  103.8  1200000.0   PETR
1  2026-09-22  103.2  105.0  101.7  102.4   980000.0   PETR
2  2026-09-23    NaN  104.8  100.5  103.1  1150000.0   PETR
3  2026-09-24  102.1  106.3  101.2  105.9       <NA>   PETR
4  2026-09-25  105.3  108.0    NaN  107.2  1300000.0   PETR
5  2026-09-28  106.2  108.4  104.8    NaN  1280000.0   PETR
6  2026-09-29  107.1  110.2  105.9  109.4  1400000.0   PETR
7  2026-09-30    NaN  111.0  107.0  110.1  1380000.0   PETR
8  2026-10-01  109.0  112.5  108.2  111.7       <NA>   PETR
9  2026-10-02  110.4  113.0  109.5  112.3  1500000.0   PETR
10 2026-09-21   55.0   56.2   54.5   55.9   700000.0  OTHER
11 2026-09-22   55.8   56.5   55.1   56.0   720000.0  OTHER
12 2026-09-23   56.1   57.0   55.4   56.7   690000.0  OTHER
13 2026-09-24   55.6   57.2   55.0   56.8   750000.0  OTHER
14 2026-09-25   57.0   58.1   56.3   57.6   810000.0  OTHER

Две акции через merge():

,Date,Open_PETR,High_PETR,Low_PETR,Close_PETR,Volume_PETR,Ticker_PETR,Open_OTHER,High_OTHER,Low_OTHER,Close_OTHER,Volume_OTHER,Ticker_OTHER
0,2026-09-21,101.5,104.2,100.8,103.8,1200000.0,PETR,55.0,56.2,54.5,55.9,700000.0,OTHER
1,2026-09-22,103.2,105.0,101.7,102.4,980000.0,PETR,55.8,56.5,55.1,56.0,720000.0,OTHER
2,2026-09-23,NaN,104.8,100.5,103.1,1150000.0,PETR,56.1,57.0,55.4,56.7,690000.0,OTHER
3,2026-09-24,102.1,106.3,101.2,105.9,<NA>,PETR,55.6,57.2,55.0,56.8,750000.0,OTHER
4,2026-09-25,105.3,108.0,NaN,107.2,1300000.0,PETR,57.0,58.1,56.3,57.6,810000.0,OTHER
5,2026-09-28,106.2,108.4,104.8,NaN,1280000.0,PETR,NaN,NaN,NaN,NaN,NaN,NaN
6,2026-09-29,107.1,110.2,105.9,109.4,1400000.0,PETR,NaN,NaN,NaN,NaN,NaN,NaN
7,2026-09-30,NaN,111.0,107.0,110.1,1380000.0,PETR,NaN,NaN,NaN,NaN,NaN,NaN
8,2026-10-01,109.0,112.5,108.2,111.7,<NA>,PETR,NaN,NaN,NaN,NaN,NaN,NaN
9,2026-10-02,110.4,113.0,109.5,112.3,1500000.0,PETR,NaN,NaN,NaN,NaN,NaN,NaN